### PR TITLE
Moved project to .NET Standard 2.0

### PR DESCRIPTION
**Pull request by roman-boltunov**

### CODE REVIEW

**Comment by roman-boltunov** [comment]
Any updates on this one?

@davidchesnut sorry, I don't really know whom should I write a message to, this repository seems pretty abandoned with no active contributors. I saw you contributed some bits to this repository and you're on OfficeDev group, could you please help with reviewing and merging this PR?

**Comment by davidchesnut** [comment]
Hi @roman-boltunov , sorry for the late reply. This isn't a repo I actively work on. I'm checking around to see if I can track down someone who can review the PR and keep an eye on the repo. We appreciate the contribution you proposed in this PR!

Thanks,
David

**Comment by roman-boltunov** [comment]
Thanks for answer, David!

**Comment by roman-boltunov** [comment]
Any updates on this one? We're going to use it in production.

**Comment by davidchesnut** [comment]
Hi @roman-boltunov , I'm still working with folks to get some help on this. The conversation thread I started to track down some help had died down, so I revived it. I'm hoping to have more info before the end of the week.

Thanks,
David

**Comment by davidchesnut** [comment]
Hi @roman-boltunov , the original owner if this repo is no longer available, but I did find someone who has taken over. They said they would follow up with you soon. 

Thanks,
David

**Comment by davidchesnut** [comment]
Hi @roman-boltunov, I discussed this repo more with the team that took over this repo and learned that this project is not taking public contributions at this time. I'm going to archive the repo to put it into read-only mode so that folks know it is not active.

I just want to be sure you are aware. This will close your PR. I'll archive the repo in a couple days. Please let me know if you need anything regarding this repo.

Thanks,
David

**Comment by roman-boltunov** [comment]
Hey David, thank you for notifying about this. Will this library still be available via NuGet?

**Comment by davidchesnut** [comment]
Hi @roman-boltunov , yes it will still be available on NuGet. Thanks!

**Comment by davidchesnut** [comment]
Closing this PR since the repo is being archived.

**Pull request closed without merging**
